# https://github.com/JasonEtco/slash-assign-action#usage
name: Slash assign

on:
  schedule:
    - cron: 0 0 * * *
  issue_comment:
    types: [created]

jobs:
  slash_assign:
    if: >
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/assign')) ||
      github.event_name == 'schedule'
    runs-on: ubuntu-latest
    env:
      ACTION_PATH: .github/actions/slash-assign-action
    steps:
      # not yet published
      # https://github.com/JasonEtco/slash-assign-action/issues/1
      - name: Check out GitHub Action
        uses: actions/checkout@v2
        with:
          repository: JasonEtco/slash-assign-action
          ref: 842404647dfd10109c8c4feb3e776807eb5e2071
          path: ${{ env.ACTION_PATH }}
      - name: Compile the Action
        run: |
          npm install
          npm build
        working-directory: ${{ env.ACTION_PATH }}

      - name: Assign the user or unassign stale assignments
        uses: ./${{ env.ACTION_PATH }}
